### ISSUE TITLE
SPD goes into an infinite loop getting first page of submissions

### ISSUE THREAD

**Issue by Kuroonehalf** [skwerlman/SPD#1]
As of a few weeks ago SPD has stopped working correctly for me, and now it always gets stuck infinitely looping trying to obtain the first page of submissions from the user given. 
I made no modifications to the code recently that coincide with this change, and I just tried the newest version of the code and the exact same problem happens, so I'm fairly certain the issue is not caused by me.

My guess would be that reddit has changed something about how it displays entries in those pages that makes it so the program is incorrectly reading through it. Unfortunately I don't know how to more accurately diagnose what that change might be.

I'm running on Windows 8.1 x64.

In the old code:
![command_prompt_-_python__spd_modded py_mittrinilli](https://cloud.githubusercontent.com/assets/12227163/17271284/2155ee1a-566f-11e6-8bd9-469e98b1f3a9.png)

In the newest code:
![administrator_windows_command_processor_-_python_ 2](https://cloud.githubusercontent.com/assets/12227163/17271265/dae7390c-566e-11e6-8562-eee344d00986.png)

**Comment by Kuroonehalf** [comment]
Another sign of this weird behavior: if I give it a user who has less than a page of submissions (<25), it just says "getting https://www.reddit.com/user/TheDarksideofSnow/submitted/" and ends the execution without downloading any of the pictures.

![command_prompt 5](https://cloud.githubusercontent.com/assets/12227163/17271389/15aa78ee-5672-11e6-93b5-1d31e24e03ec.png)

**Comment by skwerlman** [comment]
Which version of python are you using?

The tool is working for me on Python 3.5.2...

**Comment by Kuroonehalf** [comment]
Seems I'm using 3.5.1. Lemme upgrade to 3.5.2 and try again.

**Comment by Kuroonehalf** [comment]
Nope, still the same problem happening. :<

**Comment by skwerlman** [comment]
i'm gonna throw together a version with a bunch of debug statements and push it to a separate branch. ill link it here when ready

**Comment by skwerlman** [comment]
sorry for the delay; real life blah blah blah

the debug build is up: ~~310589a~~ 07db31b (fixed a missing global)

I switched out my dumb logger for zenlog, so that's a new dep.
I moved some parsing to use bs4, also a new dep.

I also noticed some weirdness in `page_get_next_page` which i fixed.

Also, (and i'm just noticing this now, whoops) I had done a bunch of minor refactoring all over the place, and never committed it, so that's in there now.

Lastly, I now rely on the user having added `wget` to their path, and don't have a hardcoded fallback, so if you were relying on the fallback, it won't work.

**Comment by Kuroonehalf** [comment]
No problemo!

And here's what I got:
![command_prompt 6](https://cloud.githubusercontent.com/assets/12227163/17440813/21edcbe8-5b26-11e6-8c0b-e07419398a46.png)

**Comment by Kuroonehalf** [comment]
Alright, this is what I get when I give it the reddit username TheDarkSideofSnow: http://pastebin.com/LN0bA2sY

None of the images get downloaded, but if I do "wget https://i.imgur.com/YGjtUEr.png" (the first image it tries to download from there) in my terminal it downloads just fine, so I'm not sure the problem is the wget command.

**Comment by Kuroonehalf** [comment]
Wait! It is downloading fine after all, but it's downloading the images to C:\Users\Kuro\Pictures\SPD\ [username] instead of the SPD folder. Is this intended?

Either way, I can modify the destination folder manually so this seems to be solved. Apologies, and thanks for the help!

I have a couple suggestions for ways to improve the program that I'd actually implemented in my personal modded version. I'll make new issue threads for them.

**Comment by skwerlman** [comment]
it is intended (it also separates by album), though maybe it should be configurable...

**Comment by skwerlman** [comment]
This issue is resolved; closing
