### ISSUE TITLE
Gfycat animated image quality prioritization

### ISSUE THREAD

**Issue by Kuroonehalf** [skwerlman/SPD#2]
Right now as far as I can tell SPD is always downloading gfycat webms as gifs*. This is a problem not only because it creates horribly compressed animated images, but the file size is waaaay bigger and takes really long to download. For reference, a regular 1.2MB webm was over 80MB as gif. 9 times out of 10 there's better quality versions of the animated image available, so gif should always be last resort.

I concocted what I think is a method to always get the best animated image available from gfycat,  Essentially, we want to see if a version of the file exists in this order:
- fat.gfycat.com/link.webm - Best quality webm available.
- giant.gfycat.com/link.webm - The standard definition webm.
- zippy.gfycat.com/link.webm - Lower quality webm. Still better than gif.
- giant.gfycat.com/link.gif - If for some reason it doesn't have any of the above versions, it resorts to grabbing the gif.

You go through them in order and check the exit code of wget. If it's 1 then it failed to find that version of the webm, so it tries the next one in the quality chain. However, I was using the wget python package to do this instead of the wget executable, so I'm not sure if this exit code business works the same, but I figure it should be similar.
Ideally you'd be able to check if the file exists without using wget, but I didn't find a command that did that. 

*As I mentioned at the start, webms are always being downloaded as gifs, even when the webm_as_gif flag is set to False. Could you please check if it's working correctly on your end?

**Comment by skwerlman** [comment]
One of the reasons it downloads as .gif by default is that .webm is not yet widely supported by file browsers or OS image viewers.

As for the flag not working, I'll check that right now.

Lastly, I'm adding a config file for some of the more obscure/complex commandline options and dropping the flags for them. When I do, I think I'll make the `--webm-as-gif` function as now, but make the quality level follow a config option.

**Comment by skwerlman** [comment]
Figured out why it wasn't ever trying to d/l webms:

```
                                                                 vvvvv
(https?://(?:gfycat\.com/[a-zA-Z]+?|giant\.gfycat\.com/[a-zA-Z]+?\.gif|imgur\.com/(?:[a-zA-Z0-9]{7}|[a-zA-Z0-9]{5})|imgur\.com/a/[a-zA-Z0-9]{5}|imgur\.com/gallery/[a-zA-Z0-9]{5}|i\.imgur\.com/(?:[a-zA-Z0-9]{7}|[a-zA-Z0-9]{5})\.(?:[a-z]{3,4})(?:\?[0-9]+?)?))
                                                                 ^^^^^
```

Will push a fix for it soon.

Also, I think I'll make the default webm quality giant, since it makes code easier to write until I implement the config file.

**Comment by skwerlman** [comment]
I pushed a fix for the webm download issue, is it working for you?

**Comment by skwerlman** [comment]
Actually, after some testing, while webm downloading _does_ work, I just realized why your suggestion is better than mine. I was unaware that gfycat did not simply duplicate each upload in various qualities, or that an image could exist on only some of the servers. I will be working to implement the flow you describe.

**Comment by skwerlman** [comment]
looking at the multitude of problems in the current codebase, I'm going to rewrite the entire program, hence the wontfix + close
